name: deploy news-api
on:
  push:
    branches:
      - develop
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: checkout
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: build with gradle
        run: |
          cd ./ccs/news-api
          chmod +x ./gradlew
          ./gradlew build

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_ID }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: build and push image
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./ccs/news-api/Dockerfile
          push: true
          repository: ${{ secrets.DOCKERHUB_ID }}/news
          tags: ${{ github.sha }}, latest
          build-args: |
            DB_URL=${{ secrets.DB_ENDPOINT }}

      - name: deploy image
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST_DEPLOYER }}
          username: ${{ secrets.HOST_DEPLOYER_USERNAME }}
          key: ${{ secrets.SSH_DEPLOYER }}
          port: 22
          script: |
            kubectl set image deployment/news-deployment news=${{ secrets.DOCKERHUB_ID }}/news:${{ github.sha }}
            kubectl rollout restart deployment/news-deployment